"""
train_classifier.py
===================
MobileNetV3-Small behavior classifier.
Input : 224×224 RGB crops (generated by 03_generate_crops.py)
Output: 7-class behavior softmax

Handles class imbalance via:
  • WeightedRandomSampler
  • Class-weighted CrossEntropyLoss

Run:
    !python train/train_classifier.py --epochs 50
"""

import torch
import torch.nn as nn
import torch.cuda.amp as amp_module
import torchvision.transforms as T
from torchvision.models import mobilenet_v3_small, MobileNet_V3_Small_Weights
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler, random_split
from pathlib import Path
from PIL import Image
import json
import time
import argparse
import sys
import numpy as np
from datetime import datetime

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from scripts.setup_drive import CROPS_DIR, MODELS_DIR, LOGS_DIR  # type: ignore


# ─────────────────────────────────────────────────────────────────────────────
def _verify_gpu() -> str:
    """Print GPU info, enable A100 hardware flags, raise if no GPU found."""
    if not torch.cuda.is_available():
        raise RuntimeError(
            "No CUDA GPU found. Set runtime to A100: "
            "Runtime → Change runtime type → A100 GPU"
        )
    name = torch.cuda.get_device_name(0)
    vram = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f"  🖥️  GPU  : {name}")
    print(f"  💾 VRAM : {vram:.1f} GB")
    # TF32: A100 tensor cores run matmul in TF32 natively (~3x vs float32).
    # PyTorch disables it by default for reproducibility — safe to enable for training.
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32       = True
    # cuDNN auto-tuner — benchmarks conv kernels on first batch, then uses fastest
    torch.backends.cudnn.benchmark        = True
    print("  ⚡ TF32 enabled  |  cuDNN benchmark ON")
    return "cuda"

BEHAVIORS = [
    "standing", "eating", "walking", "drinking",
    "lying_down", "rumination", "sleeping",
]
NUM_CLASSES = len(BEHAVIORS)

# ─────────────────────────────────────────────────────────────────────────────
# Augmentation
# ─────────────────────────────────────────────────────────────────────────────
TRAIN_TRANSFORM = T.Compose([
    T.RandomHorizontalFlip(),
    T.RandomVerticalFlip(p=0.0),   # top-down view: no vertical flip
    T.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.2, hue=0.05),
    T.RandomAffine(degrees=10, translate=(0.05, 0.05), scale=(0.9, 1.1)),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

VAL_TRANSFORM = T.Compose([
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

# Inference transform (re-exported for pipeline.py)
INFERENCE_TRANSFORM = VAL_TRANSFORM


# ─────────────────────────────────────────────────────────────────────────────
# Dataset
# ─────────────────────────────────────────────────────────────────────────────
class BehaviorCropDataset(Dataset):
    def __init__(self, crops_dir: Path, transform=None):
        self.transform = transform
        self.samples: list[tuple[str, int]] = []
        self.class_counts: dict[str, int] = {b: 0 for b in BEHAVIORS}

        for class_idx, behavior in enumerate(BEHAVIORS):
            beh_dir = crops_dir / behavior
            if not beh_dir.exists():
                continue
            imgs = list(beh_dir.glob("*.jpg")) + list(beh_dir.glob("*.png"))
            for img_path in imgs:
                self.samples.append((str(img_path), class_idx))
                self.class_counts[behavior] += 1

        print(f"  📦 Dataset: {len(self.samples)} crops total")
        for b, c in self.class_counts.items():
            status = "✅" if c >= 200 else ("⚠️ " if c > 0 else "❌")
            print(f"     {status} {b:15s}: {c}")

    def get_weighted_sampler(self) -> WeightedRandomSampler:
        totals = [self.class_counts[b] for b in BEHAVIORS]
        weights = [1.0 / max(c, 1) for c in totals]
        sample_weights = [weights[label] for _, label in self.samples]
        return WeightedRandomSampler(sample_weights, len(sample_weights), replacement=True)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        img = Image.open(img_path).convert("RGB")
        if self.transform:
            img = self.transform(img)
        return img, label


# ─────────────────────────────────────────────────────────────────────────────
# Model
# ─────────────────────────────────────────────────────────────────────────────
class BehaviorClassifier(nn.Module):
    def __init__(self, num_classes: int = NUM_CLASSES, dropout: float = 0.3):
        super().__init__()
        backbone = mobilenet_v3_small(weights=MobileNet_V3_Small_Weights.DEFAULT)
        in_features = backbone.classifier[3].in_features
        backbone.classifier[3] = nn.Identity()
        self.backbone = backbone
        self.classifier = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(in_features, num_classes),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.classifier(self.backbone(x))


# ─────────────────────────────────────────────────────────────────────────────
# Training
# ─────────────────────────────────────────────────────────────────────────────
def train_classifier(
    crops_dir: Path = CROPS_DIR,
    epochs: int = 50,
    batch_size: int = 256,  # MobileNetV3-Small is tiny; A100 handles 256 easily
    lr: float = 1e-4,
    val_split: float = 0.2,
    device: str = "cuda",
) -> dict:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    exp_name  = f"classifier_{timestamp}"
    out_dir   = MODELS_DIR / exp_name
    out_dir.mkdir(parents=True, exist_ok=True)

    device = _verify_gpu()   # fails fast if running on CPU by mistake

    # ── Resolve crops path: prefer local NVMe copy over Drive ────────────────
    # Drive throttles on thousands of small JPEG reads during training.
    # Run the 'Copy Dataset to Local NVMe' notebook cell to pre-copy crops once.
    LOCAL_CROPS = Path("/content/local_crops")
    if LOCAL_CROPS.exists() and any(LOCAL_CROPS.iterdir()):
        crops_dir = LOCAL_CROPS
        print(f"  🚀 Using LOCAL NVMe crops: {LOCAL_CROPS}")
    else:
        print(f"  📂 Using Drive crops (slow). Run 'Copy to Local NVMe' cell for faster training.")

    print(f"\n{'='*60}")
    print(f"  🧠 Classifier Experiment : {exp_name}")
    print(f"  Crops dir  : {crops_dir}")
    print(f"  Epochs     : {epochs}  |  Batch: {batch_size}  |  LR: {lr}")
    print(f"  Device     : {device}")
    print(f"{'='*60}\n")


    # ── Dataset ──────────────────────────────────────────────────────────────
    full_ds = BehaviorCropDataset(crops_dir, transform=None)
    n = len(full_ds)
    n_val = int(n * val_split)
    n_train = n - n_val
    generator = torch.Generator().manual_seed(42)
    train_ds, val_ds = random_split(full_ds, [n_train, n_val], generator=generator)

    # Hacky but correct: apply per-split transform by wrapping
    class _SubsetWithTransform(Dataset):
        def __init__(self, subset, transform):
            self.subset = subset
            self.transform = transform
        def __len__(self): return len(self.subset)
        def __getitem__(self, idx):
            img_path, label = self.subset.dataset.samples[self.subset.indices[idx]]
            img = Image.open(img_path).convert("RGB")
            if self.transform:
                img = self.transform(img)
            return img, label

    train_set = _SubsetWithTransform(train_ds, TRAIN_TRANSFORM)
    val_set   = _SubsetWithTransform(val_ds,   VAL_TRANSFORM)

    # Build weighted sampler — one weight per train sample based on its class count.
    # class_weights[label] = 1 / count(label) so rare classes get sampled more.
    # This actually applies the imbalance fix — the old code defined it but never used it.
    class_inv_freq = [1.0 / max(full_ds.class_counts[b], 1) for b in BEHAVIORS]
    train_sample_weights = [
        class_inv_freq[full_ds.samples[i][1]]   # full_ds.samples[i] = (path, label_idx)
        for i in train_ds.indices
    ]
    train_sampler = WeightedRandomSampler(
        train_sample_weights, len(train_sample_weights), replacement=True
    )

    # num_workers=0 is required on Colab — Drive-backed DataLoaders deadlock
    # with num_workers > 0 (forked workers can’t access the mounted Drive).
    # pin_memory + non_blocking — overlaps CPU→GPU transfer with compute on A100.
    train_loader = DataLoader(
        train_set, batch_size=batch_size, num_workers=0,
        pin_memory=True, sampler=train_sampler
    )
    val_loader = DataLoader(
        val_set, batch_size=batch_size, num_workers=0,
        pin_memory=True, shuffle=False
    )

    # ── Model ────────────────────────────────────────────────────────────────
    model = BehaviorClassifier().to(device)

    # torch.compile — compiles model graph for A100 Triton kernels.
    # Gives 10–30% throughput boost on small models like MobileNetV3.
    # Falls back gracefully if PyTorch < 2.0.
    if hasattr(torch, "compile"):
        try:
            model = torch.compile(model)
            print("  ⚡ torch.compile() enabled (A100 Triton kernels)")
        except Exception as e:
            print(f"  ⚠️  torch.compile skipped: {e}")

    # AMP GradScaler — handles gradient scaling for float16/bfloat16 stability.
    # autocast() wraps forward + loss; scaler wraps backward + optimizer step.
    scaler = amp_module.GradScaler()

    # Class-weighted loss
    counts = [full_ds.class_counts[b] for b in BEHAVIORS]
    total  = sum(counts)
    class_weights = torch.tensor(
        [total / max(c * NUM_CLASSES, 1) for c in counts], dtype=torch.float32
    ).to(device)
    criterion = nn.CrossEntropyLoss(weight=class_weights)

    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    best_val_acc = 0.0
    history = []
    t_start = time.time()

    for epoch in range(epochs):
        # Train
        model.train()
        t_loss = t_cor = t_tot = 0
        for imgs, labels in train_loader:
            # non_blocking overlaps CPU→GPU copy with GPU compute — free speedup
            imgs   = imgs.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            # set_to_none=True is faster than zero_grad() — skips memset
            optimizer.zero_grad(set_to_none=True)

            # AMP forward pass — bfloat16 on A100 is ~2× faster than float32
            with amp_module.autocast(device_type="cuda"):
                out  = model(imgs)
                loss = criterion(out, labels)

            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()

            t_loss += loss.item()
            preds   = out.detach().argmax(1)
            t_cor  += (preds == labels).sum().item()
            t_tot  += labels.size(0)
        scheduler.step()

        # Validate — no grad, no AMP needed for val (but autocast is fine too)
        model.eval()
        v_loss = v_cor = v_tot = 0
        with torch.no_grad():
            for imgs, labels in val_loader:
                imgs   = imgs.to(device, non_blocking=True)
                labels = labels.to(device, non_blocking=True)
                with amp_module.autocast(device_type="cuda"):
                    out  = model(imgs)
                    loss = criterion(out, labels)
                v_loss += loss.item()
                preds   = out.argmax(1)
                v_cor  += (preds == labels).sum().item()
                v_tot  += labels.size(0)

        train_acc = t_cor / max(t_tot, 1)
        val_acc   = v_cor / max(v_tot, 1)
        lr_now    = scheduler.get_last_lr()[0]

        log = dict(
            epoch      = epoch + 1,
            train_loss = round(t_loss / max(len(train_loader), 1), 4),
            train_acc  = round(train_acc, 4),
            val_loss   = round(v_loss   / max(len(val_loader), 1),   4),
            val_acc    = round(val_acc,   4),
            lr         = lr_now,
        )
        history.append(log)
        print(
            f"  Epoch [{epoch+1:3d}/{epochs}] "
            f"Loss: {log['train_loss']:.4f} | "
            f"TrainAcc: {train_acc:.3f} | "
            f"ValAcc: {val_acc:.3f} | "
            f"LR: {lr_now:.2e}"
        )

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            torch.save(model.state_dict(), out_dir / "best_classifier.pth")
            print(f"    💾 New best saved (val_acc={val_acc:.4f})")

    t_end = time.time()

    # ── Metrics ──────────────────────────────────────────────────────────────
    metrics = {
        "experiment_id"     : exp_name,
        "timestamp"         : timestamp,
        "phase"             : "behavior_classification",
        "model"             : "MobileNetV3-Small",
        "behaviors"         : BEHAVIORS,
        "best_val_accuracy" : round(best_val_acc, 4),
        "duration_minutes"  : round((t_end - t_start) / 60, 1),
        "hyperparameters"   : dict(
            epochs=epochs, batch_size=batch_size, lr=lr, val_split=val_split
        ),
        "class_counts"      : full_ds.class_counts,
        "history"           : history,
    }

    log_dir  = LOGS_DIR / exp_name
    log_dir.mkdir(parents=True, exist_ok=True)
    (log_dir / "metrics.json").write_text(json.dumps(metrics, indent=2))

    print(f"\n  ✅ Best Val Accuracy: {best_val_acc:.4f}")
    print(f"  Model  : {out_dir / 'best_classifier.pth'}")
    print(f"  Log    : {log_dir / 'metrics.json'}")

    return metrics


# ─────────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs",    type=int,   default=50)
    parser.add_argument("--batch",     type=int,   default=256,
                        help="Batch size. A100=256 for MobileNetV3; halve if OOM.")
    parser.add_argument("--lr",        type=float, default=1e-4)
    parser.add_argument("--val_split", type=float, default=0.2)
    parser.add_argument("--device",    type=str,   default="cuda")
    args = parser.parse_args()

    train_classifier(
        epochs    = args.epochs,
        batch_size= args.batch,
        lr        = args.lr,
        val_split = args.val_split,
        device    = args.device,
    )


if __name__ == "__main__":
    main()
